### ISSUE TITLE
[E][bme280.sensor:146]: Communication with BME280 failed!

### ISSUE THREAD

**Issue by Klapperman** [hubertjanhickinson/OrconWifiController#2]
After configuring the OrconWifiController and using the default configuration there is an error in the log. Afterwards the defined sensors humidity, pressure and temperature are non-functional. The board edition is version 1.3.

With the following error: **[18:45:14][E][bme280.sensor:146]: Communication with BME280 failed!**

> INFO Reading configuration /config/esphome/mvtest13.yaml...
> INFO Starting log output from mvtest13.local using esphome API
> INFO Connecting to mvtest13.local:6053 (192.168.20.160)
> INFO Successfully connected to mvtest13.local
> [18:45:13][I][app:105]: ESPHome version 1.18.0 compiled on Jun  9 2021, 18:39:24
> [18:45:13][C][wifi:443]: WiFi:
> [18:45:13][C][wifi:303]:   SSID: [redacted]
> [18:45:13][C][wifi:304]:   IP Address: 192.168.20.160
> [18:45:13][C][wifi:306]:   BSSID: [redacted]
> [18:45:13][C][wifi:307]:   Hostname: 'mvtest13'
> [18:45:13][C][wifi:311]:   Signal strength: -64 dB ▂▄▆█
> [18:45:13][C][wifi:315]:   Channel: 11
> [18:45:13][C][wifi:316]:   Subnet: 255.255.255.0
> [18:45:13][C][wifi:317]:   Gateway: 192.168.20.1
> [18:45:13][C][wifi:318]:   DNS1: 1.1.1.1
> [18:45:13][C][wifi:319]:   DNS2: 8.8.8.8
> [18:45:13][C][i2c:028]: I2C Bus:
> [18:45:13][C][i2c:029]:   SDA Pin: GPIO4
> [18:45:13][C][i2c:030]:   SCL Pin: GPIO5
> [18:45:13][C][i2c:031]:   Frequency: 50000 Hz
> [18:45:13][I][i2c:033]: Scanning i2c bus for active devices...
> [18:45:13][I][i2c:049]: Found no i2c devices!
> [18:45:14][C][esp8266_pwm:022]: ESP8266 PWM:
> [18:45:14][C][esp8266_pwm:023]:   Pin: GPIO12 (Mode: OUTPUT)
> [18:45:14][C][esp8266_pwm:024]:   Frequency: 1000.0 Hz
> [18:45:14][C][esp8266_pwm:025]:   Inverted: YES
> [18:45:14][C][switch.gpio:042]: GPIO Switch 'mv_unit_speed_bypass_test'
> [18:45:14][C][switch.gpio:043]:   Pin: GPIO15 (Mode: OUTPUT)
> [18:45:14][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to OFF)
> [18:45:14][C][logger:189]: Logger:
> [18:45:14][C][logger:190]:   Level: DEBUG
> [18:45:14][C][logger:191]:   Log Baud Rate: 115200
> [18:45:14][C][logger:192]:   Hardware UART: UART0
> [18:45:14][C][light:178]: Light 'mv_unit_speed_test'
> [18:45:14][C][light:180]:   Default Transition Length: 1.0s
> [18:45:14][C][light:181]:   Gamma Correct: 1.00
> [18:45:14][C][pulse_counter:147]: Pulse Counter 'mv_tacho_test'
> [18:45:14][C][pulse_counter:147]:   Unit of Measurement: 'pulses/min'
> [18:45:14][C][pulse_counter:147]:   Accuracy Decimals: 0
> [18:45:14][C][pulse_counter:147]:   Icon: 'mdi:pulse'
> [18:45:14][C][pulse_counter:148]:   Pin: GPIO14 (Mode: INPUT)
> [18:45:14][C][pulse_counter:149]:   Rising Edge: INCREMENT
> [18:45:14][C][pulse_counter:150]:   Falling Edge: DISABLE
> [18:45:14][C][pulse_counter:151]:   Filtering pulses shorter than 250 µs
> [18:45:14][C][pulse_counter:152]:   Update Interval: 10.0s
> [18:45:14][C][pulse_width:020]: Pulse Width 'mv_speed_requested_test'
> [18:45:14][C][pulse_width:020]:   Unit of Measurement: 's'
> [18:45:14][C][pulse_width:020]:   Accuracy Decimals: 8
> [18:45:14][C][pulse_width:020]:   Icon: 'mdi:timer-outline'
> [18:45:14][C][pulse_width:021]:   Update Interval: 10.0s
> [18:45:14][C][pulse_width:022]:   Pin: GPIO13 (Mode: INPUT)
> [18:45:14][C][bme280.sensor:142]: BME280:
> [18:45:14][C][bme280.sensor:143]:   Address: 0x76
> _[18:45:14][E][bme280.sensor:146]: Communication with BME280 failed!_
> [18:45:14][C][bme280.sensor:155]:   IIR Filter: OFF
> [18:45:14][C][bme280.sensor:156]:   Update Interval: 10.0s
> [18:45:14][C][bme280.sensor:158]:   Temperature 'OrconTemp'
> [18:45:14][C][bme280.sensor:158]:     Device Class: 'temperature'
> [18:45:14][C][bme280.sensor:158]:     Unit of Measurement: '°C'
> [18:45:14][C][bme280.sensor:158]:     Accuracy Decimals: 1
> [18:45:14][C][bme280.sensor:159]:     Oversampling: 16x
> [18:45:14][C][bme280.sensor:160]:   Pressure 'OrconPressure'
> [18:45:14][C][bme280.sensor:160]:     Device Class: 'pressure'
> [18:45:14][C][bme280.sensor:160]:     Unit of Measurement: 'hPa'
> [18:45:14][C][bme280.sensor:160]:     Accuracy Decimals: 1
> [18:45:14][C][bme280.sensor:161]:     Oversampling: 16x
> [18:45:14][C][bme280.sensor:162]:   Humidity 'OrconHumidity'
> [18:45:14][C][bme280.sensor:162]:     Device Class: 'humidity'
> [18:45:14][C][bme280.sensor:162]:     Unit of Measurement: '%'
> [18:45:14][C][bme280.sensor:162]:     Accuracy Decimals: 1
> [18:45:14][C][bme280.sensor:163]:     Oversampling: 16x
> [18:45:14][C][captive_portal:169]: Captive Portal:
> [18:45:14][C][ota:029]: Over-The-Air Updates:
> [18:45:14][C][ota:030]:   Address: mvtest13.local:8266
> [18:45:14][C][api:095]: API Server:
> [18:45:14][C][api:096]:   Address: mvtest13.local:6053
> [18:45:16][C][pulse_width:026]: 'mv_speed_requested_test' - Got pulse width 0.000 s
> [18:45:16][D][sensor:099]: 'mv_speed_requested_test': Sending state 0.00005 s with 8 decimals of accuracy
> [18:45:16][D][pulse_counter:159]: 'mv_tacho_test': Retrieved counter: 300.00 pulses/min
> [18:45:16][D][sensor:099]: 'mv_tacho_test': Sending state 300.00000 pulses/min with 0 decimals of accuracy
> [18:45:26][C][pulse_width:026]: 'mv_speed_requested_test' - Got pulse width 0.000 s
> [18:45:26][D][sensor:099]: 'mv_speed_requested_test': Sending state 0.00005 s with 8 decimals of accuracy
> [18:45:26][D][pulse_counter:159]: 'mv_tacho_test': Retrieved counter: 288.00 pulses/min
> [18:45:26][D][sensor:099]: 'mv_tacho_test': Sending state 288.00000 pulses/min with 0 decimals of accuracy
> [18:45:36][C][pulse_width:026]: 'mv_speed_requested_test' - Got pulse width 0.000 s
> [18:45:36][D][sensor:099]: 'mv_speed_requested_test': Sending state 0.00005 s with 8 decimals of accuracy
> [18:45:36][D][pulse_counter:159]: 'mv_tacho_test': Retrieved counter: 234.00 pulses/min
> [18:45:36][D][sensor:099]: 'mv_tacho_test': Sending state 234.00000 pulses/min with 0 decimals of accuracy
> [18:45:46][C][pulse_width:026]: 'mv_speed_requested_test' - Got pulse width 0.000 s
> [18:45:46][D][sensor:099]: 'mv_speed_requested_test': Sending state 0.00005 s with 8 decimals of accuracy
> [18:45:46][D][pulse_counter:159]: 'mv_tacho_test': Retrieved counter: 222.00 pulses/min
> [18:45:46][D][sensor:099]: 'mv_tacho_test': Sending state 222.00000 pulses/min with 0 decimals of accuracy

ESPhome YAML (removed home SSID and passwords)
[mvtest13.zip](https://github.com/hubertjanhickinson/OrconWifiController/files/6625511/mvtest13.zip)

**Comment by hubertjanhickinson** [comment]
At the time of building a new batch of PCBs, it was untested to have a temperature/humidity sensor. Once the PCBs came in, I could test it, and so I added it to the default configuration. As they were not available when ordering all the parts, I chose to leave it is as is.
If you want to install a sensor, use a 5V BME280 sensor. Or contact me so I can build one for you.

**Comment by Klapperman** [comment]
Ok clear, I'll look into the need for the BME280 sensor. First I need to figure out how to OTA flash this change to the board, as currently it's seemingly not really changing anything. Thanks for the information.

**Comment by pdeelen** [comment]
Hi, can you aksplain more how to install the BME280 sensor? Thanks!

**Comment by hubertjanhickinson** [comment]
> 
> 
> Hi, can you aksplain more how to install the BME280 sensor? Thanks!

You can install one if if you make a slot in the case, to slide the sensor through. Using long pin headers you can install it on the underside of the board, just like the original sensor.
